<?php
    $title = "Marmitas da Dona Rita";
    $desenvolvedor = "Rodrigo Oliveira";

    $tutoriais = array(
        0 => array('id'=>'1', 
            'titulo'=>'Marmita Premium R$29.90',  
            'data'=>'2022-08-13', 
            'descricao'=>'Arroz, Feijão, Farofa, Milho e Legumes',
            'imagem'=>'img/img1.jpg', 
            'title_img'=>'Marmita Premium'),
        1 => array('id'=>'2', 
            'titulo'=>'Lancheira de frango R$ 27.00',  
            'data'=>'2022-08-13', 
            'descricao'=>'Lancheira de frango, bulgur, microgreens, tomate e frutas. Comida saudável fitness',
            'imagem'=>'img/img2.jpg', 
            'title_img'=>'Marmita da Casa'),
        2 => array('id'=>'3', 
            'titulo'=>'Marmita Delícia R$ 24.50', 
            'data'=>'2022-08-13', 
            'descricao'=>'Arroz, Feijão, Farofa, Frango Grelhado, Brócolis, Batata Cozida',
            'imagem'=>'img/img3.jpg', 
            'title_img'=>'Marmita Delícia'),
        3 => array('id'=>'4', 
            'titulo'=>'Marmita Compacta R$ 20.00', 
            'data'=>'2022-08-13', 
            'descricao'=>'Arroz Integral, Brócolis, Cenoura, Frango Grelhado e Batata Cozida',
            'imagem'=>'img/img4.jpg', 
            'title_img'=>'Marmita Compacta'),
        4 => array('id'=>'5', 
            'titulo'=>'Marmita Fit R$ 19.90', 
            'data'=>'2022-08-13', 
            'descricao'=>'Arroz, Feijão, Brócolis, Laranja',
            'imagem'=>'img/img5.jpg', 
            'title_img'=>'Marmita Caseira nº 5'),
        5 => array('id'=>'6', 
            'titulo'=>'Marmita Tropeira R$ 24.00', 
            'data'=>'2022-08-13', 
            'descricao'=>'Arroz, Carne assada, Linguiça blumenau, Tomate, Cenoura',
            'imagem'=>'img/img6.jpg', 
            'title_img'=>'Marmita Tropeira'),
        6 => array('id'=>'7', 
            'titulo'=>'Marmita Serrana R$ 24.00', 
            'data'=>'2022-08-13', 
            'descricao'=>'Arroz, Feijão, Macarrão, Linguiça, Farofa, Batata',
            'imagem'=>'img/img7.jpg', 
            'title_img'=>'Marmita Serrana'),
        7 => array('id'=>'8', 
            'titulo'=>'Marmita Completa Executiva R$ 22.00', 
            'data'=>'2022-08-13', 
            'descricao'=>'Arroz, Feijão, Nhoque, Frango Empanado, Cozido, banana frita e Salada',
            'imagem'=>'img/img8.jpg', 
            'title_img'=>'Marmita Completa Executiva'),
    );